// ข้อมูลคลังยาและเวชภัณฑ์ระบบ OPD คลินิกเวชกรรมนครสวรรค์เฮลท์แคร์ (196 รายการ)
// อัปเดตล่าสุด: 16/9/2569 (Standardized Pharmacological Generic Names for OCR)
const OPD_MASTER_DRUGS = [
  {
    "drug_id": "D001",
    "generic_name": "Acetylcysteine",
    "strength": "100MG",
    "dosage_form": "Sachet",
    "trade_name": "MYSOVEN 100MG. 60ซอง",
    "unit": "ซอง",
    "purchase_price": 1.83,
    "sale_price": 6,
    "stock": 63,
    "min_stock": 10,
    "drawer": "10",
    "active": true
  },
  {
    "drug_id": "D002",
    "generic_name": "Acetylcysteine",
    "strength": "200MG",
    "dosage_form": "Sachet",
    "trade_name": "MYSOVEN 200MG. 60ซอง",
    "unit": "ซอง",
    "purchase_price": 3.67,
    "sale_price": 10,
    "stock": 34,
    "min_stock": 10,
    "drawer": "10",
    "active": true
  },
  {
    "drug_id": "D003",
    "generic_name": "Acyclovir",
    "strength": "400mg",
    "dosage_form": "Tablet",
    "trade_name": "Zocovin/T.O.PHARMA",
    "unit": "เม็ด",
    "purchase_price": 2.79,
    "sale_price": 3.5,
    "stock": 47,
    "min_stock": 10,
    "drawer": "9",
    "active": true
  },
  {
    "drug_id": "D004",
    "generic_name": "Acyclovir",
    "strength": "ครีม 5gm",
    "dosage_form": "Tube",
    "trade_name": "Clinovir ครีม 5gm",
    "unit": "หลอด",
    "purchase_price": 30,
    "sale_price": 35,
    "stock": 0,
    "min_stock": 10,
    "drawer": "7",
    "active": true
  },
  {
    "drug_id": "D005",
    "generic_name": "Acyclovir",
    "strength": "ครีม 5gm",
    "dosage_form": "Tube",
    "trade_name": "MONIRAX/ T.man",
    "unit": "หลอด",
    "purchase_price": 13.33,
    "sale_price": 30,
    "stock": 1,
    "min_stock": 10,
    "drawer": "7",
    "active": true
  },
  {
    "drug_id": "D006",
    "generic_name": "Acyclovir",
    "strength": "400mg",
    "dosage_form": "Tablet",
    "trade_name": "Clinovir-400mg [BKD]",
    "unit": "เม็ด",
    "purchase_price": 4.2,
    "sale_price": 8,
    "stock": 29,
    "min_stock": 10,
    "drawer": "9",
    "active": true
  },
  {
    "drug_id": "D007",
    "generic_name": "Aescin",
    "strength": "20mg",
    "dosage_form": "Tablet",
    "trade_name": "Reparil เม็ด ขายเป็นแผง 20mg",
    "unit": "เม็ด",
    "purchase_price": 5.4,
    "sale_price": 8,
    "stock": 0,
    "min_stock": 10,
    "drawer": "",
    "active": true
  },
  {
    "drug_id": "D008",
    "generic_name": "Aescin + Diethylamine salicylate",
    "strength": "10g",
    "dosage_form": "Tube",
    "trade_name": "Reparil gel 10gm",
    "unit": "หลอด",
    "purchase_price": 65,
    "sale_price": 100,
    "stock": 4,
    "min_stock": 10,
    "drawer": "8",
    "active": true
  },
  {
    "drug_id": "D009",
    "generic_name": "Allopurinol",
    "strength": "300MG",
    "dosage_form": "Tablet",
    "trade_name": "ALLOPURINOL300MG / XANOL",
    "unit": "เม็ด",
    "purchase_price": 1.1,
    "sale_price": 3,
    "stock": 3,
    "min_stock": 10,
    "drawer": "1",
    "active": true
  },
  {
    "drug_id": "D010",
    "generic_name": "Allopurinol",
    "strength": "100mg",
    "dosage_form": "Tablet",
    "trade_name": "pipALLO 100mg",
    "unit": "เม็ด",
    "purchase_price": 0.54,
    "sale_price": 2,
    "stock": 800,
    "min_stock": 10,
    "drawer": "1",
    "active": true
  },
  {
    "drug_id": "D011",
    "generic_name": "Allopurinol",
    "strength": "100mg",
    "dosage_form": "Tablet",
    "trade_name": "ALLOPURINOL300MG 50X10'S(XANOL)",
    "unit": "เม็ด",
    "purchase_price": 1.1,
    "sale_price": 2,
    "stock": 5,
    "min_stock": 10,
    "drawer": "1",
    "active": true
  },
  {
    "drug_id": "D012",
    "generic_name": "Aluminium hydroxide + Magnesium hydroxide",
    "strength": "240 ML",
    "dosage_form": "Bottle",
    "trade_name": "Bowa Gel",
    "unit": "ขวด",
    "purchase_price": 33,
    "sale_price": 40,
    "stock": 9,
    "min_stock": 10,
    "drawer": "1",
    "active": true
  },
  {
    "drug_id": "D013",
    "generic_name": "Amitriptyline",
    "strength": "10mg",
    "dosage_form": "Tablet",
    "trade_name": "POLYTANOL 10MG S0X10'S",
    "unit": "เม็ด",
    "purchase_price": 1.13,
    "sale_price": 3,
    "stock": 250,
    "min_stock": 10,
    "drawer": "11",
    "active": true
  },
  {
    "drug_id": "D014",
    "generic_name": "Amlodipine",
    "strength": "10 mg",
    "dosage_form": "Tablet",
    "trade_name": "AMBES - (แอมเบส 10) / GPO",
    "unit": "เม็ด",
    "purchase_price": 0.11,
    "sale_price": 2,
    "stock": 184,
    "min_stock": 10,
    "drawer": "2",
    "active": true
  },
  {
    "drug_id": "D015",
    "generic_name": "Amlodipine",
    "strength": "5mg",
    "dosage_form": "Tablet",
    "trade_name": "AMBES - (แอมเบส 5) / GPO",
    "unit": "เม็ด",
    "purchase_price": 0.34,
    "sale_price": 2,
    "stock": 740,
    "min_stock": 10,
    "drawer": "2",
    "active": true
  },
  {
    "drug_id": "D016",
    "generic_name": "Amoxicillin",
    "strength": "125MG",
    "dosage_form": "Bottle",
    "trade_name": "Star mox ฟอร์ท",
    "unit": "ขวด",
    "purchase_price": 20,
    "sale_price": 30,
    "stock": 5,
    "min_stock": 10,
    "drawer": "1",
    "active": true
  },
  {
    "drug_id": "D017",
    "generic_name": "Amoxicillin",
    "strength": "250MG",
    "dosage_form": "Bottle",
    "trade_name": "Starmox ฟอร์ท 250mg รสส้ม 60ml",
    "unit": "ขวด",
    "purchase_price": 20,
    "sale_price": 30,
    "stock": 6,
    "min_stock": 10,
    "drawer": "1",
    "active": true
  },
  {
    "drug_id": "D018",
    "generic_name": "Amoxicillin + Clavulanic acid",
    "strength": "1000mg.",
    "dosage_form": "Tablet",
    "trade_name": "AMK 1000MG 10'S/pro-03 C01",
    "unit": "เม็ด",
    "purchase_price": 9.4,
    "sale_price": 12,
    "stock": 20,
    "min_stock": 10,
    "drawer": "9",
    "active": true
  },
  {
    "drug_id": "D019",
    "generic_name": "Amoxicillin + Clavulanic acid",
    "strength": "50 Mg.",
    "dosage_form": "Bottle",
    "trade_name": "Manclamine Es กลิ่นส้ม 642.9mg/5ml 50ml",
    "unit": "ขวด",
    "purchase_price": 165,
    "sale_price": 200,
    "stock": 2,
    "min_stock": 10,
    "drawer": "1",
    "active": true
  },
  {
    "drug_id": "D020",
    "generic_name": "Amoxicillin",
    "strength": "125MG",
    "dosage_form": "Bottle",
    "trade_name": "STARMOX DRY SYRUP seven starใส่กล่อง)",
    "unit": "ขวด",
    "purchase_price": 19.75,
    "sale_price": 30,
    "stock": 2,
    "min_stock": 10,
    "drawer": "1",
    "active": true
  },
  {
    "drug_id": "D021",
    "generic_name": "Amoxicillin + Clavulanic acid",
    "strength": "5ml 50ml",
    "dosage_form": "Bottle",
    "trade_name": "Manclamine Es กลิ่นส้ม 642.9mg/5ml 50ml",
    "unit": "ขวด",
    "purchase_price": 165,
    "sale_price": 200,
    "stock": 2,
    "min_stock": 10,
    "drawer": "1",
    "active": true
  },
  {
    "drug_id": "D022",
    "generic_name": "Amoxicillin",
    "strength": "500mg",
    "dosage_form": "Tablet",
    "trade_name": "Moxicap",
    "unit": "เม็ด",
    "purchase_price": 0.95,
    "sale_price": 3,
    "stock": 275,
    "min_stock": 10,
    "drawer": "3",
    "active": true
  },
  {
    "drug_id": "D023",
    "generic_name": "Methyl salicylate + Menthol + Camphor",
    "strength": "30gm",
    "dosage_form": "Box",
    "trade_name": "NEOTICA BALM /thai nakorn patana",
    "unit": "กล่อง",
    "purchase_price": 18,
    "sale_price": 30,
    "stock": 1,
    "min_stock": 10,
    "drawer": "8",
    "active": true
  },
  {
    "drug_id": "D024",
    "generic_name": "Silver sulfadiazine",
    "strength": "25 g",
    "dosage_form": "Tube",
    "trade_name": "Silverderm 25gm",
    "unit": "หลอด",
    "purchase_price": 31.5,
    "sale_price": 60,
    "stock": 1,
    "min_stock": 10,
    "drawer": "7",
    "active": true
  },
  {
    "drug_id": "D025",
    "generic_name": "Activated Charcoal",
    "strength": "200mg.",
    "dosage_form": "Tablet",
    "trade_name": "Ca-r-bon 260mg ขายเป็นแผง",
    "unit": "เม็ด",
    "purchase_price": 1.55,
    "sale_price": 3,
    "stock": 10,
    "min_stock": 10,
    "drawer": "4",
    "active": true
  },
  {
    "drug_id": "D026",
    "generic_name": "Aspirin",
    "strength": "81mg",
    "dosage_form": "Tablet",
    "trade_name": "Aspilets 81mg",
    "unit": "เม็ด",
    "purchase_price": 0.03,
    "sale_price": 1,
    "stock": 70,
    "min_stock": 10,
    "drawer": "6",
    "active": true
  },
  {
    "drug_id": "D027",
    "generic_name": "Atenolol",
    "strength": "50 mg",
    "dosage_form": "Tablet",
    "trade_name": "Atenol /อาทีนอล",
    "unit": "เม็ด",
    "purchase_price": 0.38,
    "sale_price": 2,
    "stock": 500,
    "min_stock": 10,
    "drawer": "2",
    "active": true
  },
  {
    "drug_id": "D028",
    "generic_name": "COVID-19 / Influenza A&B Antigen Test Kit (ATK)",
    "strength": "",
    "dosage_form": "Box",
    "trade_name": "WONDER DENGUE IgG/IgM-NS1 ATK ชุด",
    "unit": "ชุด",
    "purchase_price": 78,
    "sale_price": 100,
    "stock": 0,
    "min_stock": 10,
    "drawer": "ห",
    "active": true
  },
  {
    "drug_id": "D029",
    "generic_name": "Atorvastatin",
    "strength": "40 mg",
    "dosage_form": "Tablet",
    "trade_name": "Tovastin 40mg",
    "unit": "เม็ด",
    "purchase_price": 8.67,
    "sale_price": 10,
    "stock": 0,
    "min_stock": 10,
    "drawer": "3",
    "active": true
  },
  {
    "drug_id": "D030",
    "generic_name": "Atorvastatin",
    "strength": "40 mg",
    "dosage_form": "Tablet",
    "trade_name": "Chlovas 40mg/ mill med",
    "unit": "เม็ด",
    "purchase_price": 8.63,
    "sale_price": 10,
    "stock": 306,
    "min_stock": 10,
    "drawer": "3",
    "active": true
  },
  {
    "drug_id": "D031",
    "generic_name": "Atorvastatin",
    "strength": "20 mg",
    "dosage_form": "Tablet",
    "trade_name": "LIPOSTAT /siam",
    "unit": "เม็ด",
    "purchase_price": 6,
    "sale_price": 9,
    "stock": 20,
    "min_stock": 10,
    "drawer": "3",
    "active": true
  },
  {
    "drug_id": "D032",
    "generic_name": "Amoxicillin + Clavulanic acid",
    "strength": "1000 mg",
    "dosage_form": "Tablet",
    "trade_name": "AMOTIN 1000 /T.O CHEMICAL",
    "unit": "เม็ด",
    "purchase_price": 7.4,
    "sale_price": 12,
    "stock": 150,
    "min_stock": 10,
    "drawer": "3",
    "active": true
  },
  {
    "drug_id": "D033",
    "generic_name": "Azithromycin",
    "strength": "200mg",
    "dosage_form": "Bottle",
    "trade_name": "Onzet-P syrup สับปะรด 200mg/5ml เหลือง",
    "unit": "ขวด",
    "purchase_price": 81,
    "sale_price": 140,
    "stock": 1,
    "min_stock": 10,
    "drawer": "1",
    "active": true
  },
  {
    "drug_id": "D034",
    "generic_name": "Azithromycin",
    "strength": "250mg",
    "dosage_form": "Tablet",
    "trade_name": "AZITHRO /M&H",
    "unit": "เม็ด",
    "purchase_price": 8.17,
    "sale_price": 13,
    "stock": 72,
    "min_stock": 10,
    "drawer": "9",
    "active": true
  },
  {
    "drug_id": "D035",
    "generic_name": "Benzoyl peroxide",
    "strength": "60gm",
    "dosage_form": "Tube",
    "trade_name": "Benzac AC 2 1/2% gel 60gm",
    "unit": "หลอด",
    "purchase_price": 267,
    "sale_price": 350,
    "stock": 0,
    "min_stock": 10,
    "drawer": "10",
    "active": true
  },
  {
    "drug_id": "D036",
    "generic_name": "Betahistine Mesylate",
    "strength": "6 MG",
    "dosage_form": "Tablet",
    "trade_name": "MERISLON",
    "unit": "เม็ด",
    "purchase_price": 0.5,
    "sale_price": 2,
    "stock": 27,
    "min_stock": 10,
    "drawer": "11",
    "active": true
  },
  {
    "drug_id": "D037",
    "generic_name": "Betahistine Mesylate",
    "strength": "12 MG",
    "dosage_form": "Tablet",
    "trade_name": "MERISLON",
    "unit": "เม็ด",
    "purchase_price": 0.7,
    "sale_price": 3,
    "stock": 140,
    "min_stock": 10,
    "drawer": "11",
    "active": true
  },
  {
    "drug_id": "D038",
    "generic_name": "Betahistine Mesylate",
    "strength": "12 MG",
    "dosage_form": "Tablet",
    "trade_name": "BEHISTIN 12",
    "unit": "เม็ด",
    "purchase_price": 0.8,
    "sale_price": 3,
    "stock": 130,
    "min_stock": 10,
    "drawer": "11",
    "active": true
  },
  {
    "drug_id": "D039",
    "generic_name": "Betahistine Mesylate",
    "strength": "6 MG",
    "dosage_form": "Tablet",
    "trade_name": "CENTRAL POLYTRANDING",
    "unit": "เม็ด",
    "purchase_price": 0.8,
    "sale_price": 2,
    "stock": 47,
    "min_stock": 10,
    "drawer": "11",
    "active": true
  },
  {
    "drug_id": "D040",
    "generic_name": "Betamethasone valerate + Neomycin sulfate",
    "strength": "5g",
    "dosage_form": "Box",
    "trade_name": "BET-N STAR 5GM",
    "unit": "กล่อง",
    "purchase_price": 13.67,
    "sale_price": 25,
    "stock": 13,
    "min_stock": 10,
    "drawer": "8",
    "active": true
  },
  {
    "drug_id": "D041",
    "generic_name": "Betamethasone valerate + Neomycin sulfate",
    "strength": "15g",
    "dosage_form": "Box",
    "trade_name": "BETA- DIPO/ thainakorn patana",
    "unit": "กล่อง",
    "purchase_price": 39.5,
    "sale_price": 50,
    "stock": 4,
    "min_stock": 10,
    "drawer": "8",
    "active": true
  },
  {
    "drug_id": "D042",
    "generic_name": "Betamethasone valerate",
    "strength": "5g",
    "dosage_form": "Box",
    "trade_name": "clinivate BKD",
    "unit": "กล่อง",
    "purchase_price": 13.25,
    "sale_price": 25,
    "stock": 7,
    "min_stock": 10,
    "drawer": "8",
    "active": true
  },
  {
    "drug_id": "D043",
    "generic_name": "Bromhexine",
    "strength": "60ML",
    "dosage_form": "Bottle",
    "trade_name": "BROMMY SYRUP 60ML SCI STRAW BLH]",
    "unit": "ขวด",
    "purchase_price": 15.75,
    "sale_price": 30,
    "stock": 0,
    "min_stock": 10,
    "drawer": "1",
    "active": true
  },
  {
    "drug_id": "D044",
    "generic_name": "Bromhexine",
    "strength": "8 mg",
    "dosage_form": "Tablet",
    "trade_name": "GENERAL DRUG HOUSE",
    "unit": "เม็ด",
    "purchase_price": 0.1,
    "sale_price": 1,
    "stock": 1300,
    "min_stock": 10,
    "drawer": "10",
    "active": true
  },
  {
    "drug_id": "D045",
    "generic_name": "Bromhexine",
    "strength": "60ml",
    "dosage_form": "Bottle",
    "trade_name": "Brovol syrup 60ml",
    "unit": "ขวด",
    "purchase_price": 14,
    "sale_price": 30,
    "stock": 2,
    "min_stock": 10,
    "drawer": "ด",
    "active": true
  },
  {
    "drug_id": "D046",
    "generic_name": "Bromhexine",
    "strength": "60ml",
    "dosage_form": "Bottle",
    "trade_name": "Bromso  Elixir /TO",
    "unit": "ขวด",
    "purchase_price": 15,
    "sale_price": 30,
    "stock": 0,
    "min_stock": 10,
    "drawer": "ด",
    "active": true
  },
  {
    "drug_id": "D047",
    "generic_name": "Bromhexine hydrochloride",
    "strength": "60ML",
    "dosage_form": "Bottle",
    "trade_name": "ASOVON SYRUP 60ML / [MS]",
    "unit": "ขวด",
    "purchase_price": 15,
    "sale_price": 30,
    "stock": 1,
    "min_stock": 10,
    "drawer": "ด",
    "active": true
  },
  {
    "drug_id": "D048",
    "generic_name": "Bromhexine hydrochloride",
    "strength": "8mg",
    "dosage_form": "Tablet",
    "trade_name": "BROMXINE 8MG mucocin",
    "unit": "เม็ด",
    "purchase_price": 0.17,
    "sale_price": 1,
    "stock": 25,
    "min_stock": 10,
    "drawer": "10",
    "active": true
  },
  {
    "drug_id": "D049",
    "generic_name": "Brown mixture (Glycyrrhiza compound)",
    "strength": "60ml",
    "dosage_form": "Bottle",
    "trade_name": "ไอน้ำดำเสือดาว (ล) 60ML",
    "unit": "ขวด",
    "purchase_price": 15.42,
    "sale_price": 20,
    "stock": 11,
    "min_stock": 10,
    "drawer": "10",
    "active": true
  },
  {
    "drug_id": "D050",
    "generic_name": "Calcium carbonate",
    "strength": "1000mg.",
    "dosage_form": "Tablet",
    "trade_name": "CALTAB-1000MG 10X10/S[MILLIMED] (CALCIUM",
    "unit": "เม็ด",
    "purchase_price": 0.84,
    "sale_price": 10,
    "stock": 200,
    "min_stock": 10,
    "drawer": "12",
    "active": true
  },
  {
    "drug_id": "D051",
    "generic_name": "Cephalexin",
    "strength": "250 mg",
    "dosage_form": "Bottle",
    "trade_name": "TOFLEX DRY 250MG TO เปลือย (CEFALEXIN) 202",
    "unit": "ขวด",
    "purchase_price": 35.5,
    "sale_price": 50,
    "stock": 2,
    "min_stock": 10,
    "drawer": "1",
    "active": true
  },
  {
    "drug_id": "D052",
    "generic_name": "Cefdinir",
    "strength": "125mg/5ml.",
    "dosage_form": "Bottle",
    "trade_name": "DINICEF",
    "unit": "ขวด",
    "purchase_price": 135,
    "sale_price": 170,
    "stock": 5,
    "min_stock": 10,
    "drawer": "ด",
    "active": true
  },
  {
    "drug_id": "D053",
    "generic_name": "Celecoxib",
    "strength": "200MG",
    "dosage_form": "Tablet",
    "trade_name": "PAINNEX 200MG สูตร CELEBREX / [MILLIMED]",
    "unit": "เม็ด",
    "purchase_price": 5.57,
    "sale_price": 9,
    "stock": 40,
    "min_stock": 10,
    "drawer": "5",
    "active": true
  },
  {
    "drug_id": "D054",
    "generic_name": "Celecoxib",
    "strength": "200MG",
    "dosage_form": "Tablet",
    "trade_name": "CELECOXIB T.O.200MG.10'S",
    "unit": "เม็ด",
    "purchase_price": 3.5,
    "sale_price": 6,
    "stock": 150,
    "min_stock": 10,
    "drawer": "5",
    "active": true
  },
  {
    "drug_id": "D055",
    "generic_name": "Cetirizine hydrochloride",
    "strength": "10mg",
    "dosage_form": "Tablet",
    "trade_name": "CETIRIZINE /Media pharma",
    "unit": "เม็ด",
    "purchase_price": 1.18,
    "sale_price": 2,
    "stock": 200,
    "min_stock": 10,
    "drawer": "10",
    "active": true
  },
  {
    "drug_id": "D056",
    "generic_name": "Cetirizine hydrochloride",
    "strength": "60ML",
    "dosage_form": "Bottle",
    "trade_name": "ALEREST SYRUP / [ชุมชน)",
    "unit": "ขวด",
    "purchase_price": 25.25,
    "sale_price": 30,
    "stock": 3,
    "min_stock": 10,
    "drawer": "ด",
    "active": true
  },
  {
    "drug_id": "D057",
    "generic_name": "Cetirizine hydrochloride",
    "strength": "60ml",
    "dosage_form": "Bottle",
    "trade_name": "TIZINE SYRUP 60ML Sถสัม (BLH]",
    "unit": "ขวด",
    "purchase_price": 12.75,
    "sale_price": 30,
    "stock": 11,
    "min_stock": 10,
    "drawer": "ด",
    "active": true
  },
  {
    "drug_id": "D058",
    "generic_name": "Chloramphenicol",
    "strength": "5ml",
    "dosage_form": "Bottle",
    "trade_name": "Chlor-oph (คลอรอฟ) / SENG THAI COMPANY",
    "unit": "ขวด",
    "purchase_price": 26,
    "sale_price": 60,
    "stock": 4,
    "min_stock": 10,
    "drawer": "11",
    "active": true
  },
  {
    "drug_id": "D059",
    "generic_name": "Chloramphenicol",
    "strength": "5ml",
    "dosage_form": "Bottle",
    "trade_name": "CHLOR-OPH 5CC (ขายขาด) (CHLORAM)",
    "unit": "ขวด",
    "purchase_price": 26,
    "sale_price": 60,
    "stock": 0,
    "min_stock": 10,
    "drawer": "ห",
    "active": true
  },
  {
    "drug_id": "D060",
    "generic_name": "Chlorpheniramine maleate",
    "strength": "4mg",
    "dosage_form": "Tablet",
    "trade_name": "Chlorpheniramine malieate Iml 10mg Tp",
    "unit": "เม็ด",
    "purchase_price": 0.2,
    "sale_price": 1,
    "stock": 900,
    "min_stock": 10,
    "drawer": "10",
    "active": true
  },
  {
    "drug_id": "D061",
    "generic_name": "Ciprofloxacin",
    "strength": "500mg",
    "dosage_form": "Tablet",
    "trade_name": "500MG [สหแพทย์]10X10'S(FLOXCIPRO",
    "unit": "เม็ด",
    "purchase_price": 1.15,
    "sale_price": 3,
    "stock": 148,
    "min_stock": 10,
    "drawer": "9",
    "active": true
  },
  {
    "drug_id": "D062",
    "generic_name": "Ciprofloxacin",
    "strength": "250mg",
    "dosage_form": "Tablet",
    "trade_name": "250MG [สหแพทย์]10X10'S(FLOXCIPRO",
    "unit": "เม็ด",
    "purchase_price": 0.9,
    "sale_price": 2,
    "stock": 160,
    "min_stock": 10,
    "drawer": "9",
    "active": true
  },
  {
    "drug_id": "D063",
    "generic_name": "Clarithromycin",
    "strength": "250mg",
    "dosage_form": "Tablet",
    "trade_name": "CLARITH 250MG.10'S.",
    "unit": "เม็ด",
    "purchase_price": 7,
    "sale_price": 12,
    "stock": 31,
    "min_stock": 10,
    "drawer": "9",
    "active": true
  },
  {
    "drug_id": "D064",
    "generic_name": "Clindamycin",
    "strength": "300mg",
    "dosage_form": "Tablet",
    "trade_name": "Clindavid /millmed BFS",
    "unit": "เม็ด",
    "purchase_price": 3.5,
    "sale_price": 5,
    "stock": 60,
    "min_stock": 10,
    "drawer": "3",
    "active": true
  },
  {
    "drug_id": "D065",
    "generic_name": "Clotrimazole",
    "strength": "100mg",
    "dosage_form": "stick",
    "trade_name": "Starda 100mg ชนิดเหน็บช่องคลอด / seven star",
    "unit": "เม็ด",
    "purchase_price": 2,
    "sale_price": 7,
    "stock": 18,
    "min_stock": 10,
    "drawer": "4",
    "active": true
  },
  {
    "drug_id": "D066",
    "generic_name": "Clotrimazole",
    "strength": "100MG",
    "dosage_form": "Tablet",
    "trade_name": "CANDINOX",
    "unit": "เม็ด",
    "purchase_price": 2.58,
    "sale_price": 7,
    "stock": 6,
    "min_stock": 10,
    "drawer": "8",
    "active": true
  },
  {
    "drug_id": "D067",
    "generic_name": "Cloxacillin",
    "strength": "125mg",
    "dosage_form": "Bottle",
    "trade_name": "Cloxstar 125mg syrup 60 ml",
    "unit": "ขวด",
    "purchase_price": 19,
    "sale_price": 30,
    "stock": 2,
    "min_stock": 10,
    "drawer": "1",
    "active": true
  },
  {
    "drug_id": "D068",
    "generic_name": "Colchicine",
    "strength": "0.6mg",
    "dosage_form": "Tablet",
    "trade_name": "pipCHICINE 0.6",
    "unit": "เม็ด",
    "purchase_price": 0.5,
    "sale_price": 1,
    "stock": 70,
    "min_stock": 10,
    "drawer": "5",
    "active": true
  },
  {
    "drug_id": "D069",
    "generic_name": "Salicylic acid + Liquefied Phenol",
    "strength": "15ml",
    "dosage_form": "Bottle",
    "trade_name": "Con con",
    "unit": "ขวด",
    "purchase_price": 42,
    "sale_price": 70,
    "stock": 1,
    "min_stock": 10,
    "drawer": "7",
    "active": true
  },
  {
    "drug_id": "D070",
    "generic_name": "Purified Flavonoid Fraction (Diosmin + Hesperidin)",
    "strength": "500 mg",
    "dosage_form": "Tablet",
    "trade_name": "daflon 500",
    "unit": "เม็ด",
    "purchase_price": 9.6,
    "sale_price": 14,
    "stock": 90,
    "min_stock": 10,
    "drawer": "4",
    "active": true
  },
  {
    "drug_id": "D071",
    "generic_name": "Diosmectite",
    "strength": "20ml",
    "dosage_form": "Set",
    "trade_name": "DEHECTA 20X20ML JUSTRAW",
    "unit": "ซอง",
    "purchase_price": 23,
    "sale_price": 35,
    "stock": 5,
    "min_stock": 10,
    "drawer": "4",
    "active": true
  },
  {
    "drug_id": "D072",
    "generic_name": "Dextromethorphan hydrobromide",
    "strength": "15mg",
    "dosage_form": "Tablet",
    "trade_name": "DEXTROMETHORPHAN 15MG / นิวไลฟ์ ฟาร์มา",
    "unit": "เม็ด",
    "purchase_price": 0.29,
    "sale_price": 1,
    "stock": 2100,
    "min_stock": 10,
    "drawer": "10",
    "active": true
  },
  {
    "drug_id": "D073",
    "generic_name": "Dextromethorphan hydrobromide",
    "strength": "15mg",
    "dosage_form": "Tablet",
    "trade_name": "Terco-D เขียว ขายเป็นแผง",
    "unit": "เม็ด",
    "purchase_price": 1,
    "sale_price": 3,
    "stock": 100,
    "min_stock": 10,
    "drawer": "10",
    "active": true
  },
  {
    "drug_id": "D074",
    "generic_name": "Diclofenac sodium",
    "strength": "25 MG",
    "dosage_form": "Tablet",
    "trade_name": "Star rent",
    "unit": "เม็ด",
    "purchase_price": 0.12,
    "sale_price": 1,
    "stock": 200,
    "min_stock": 10,
    "drawer": "5",
    "active": true
  },
  {
    "drug_id": "D075",
    "generic_name": "Dicloxacillin sodium",
    "strength": "500mg",
    "dosage_form": "Tablet",
    "trade_name": "DOROX 500MG  M & H",
    "unit": "เม็ด",
    "purchase_price": 2.2,
    "sale_price": 4,
    "stock": 10,
    "min_stock": 10,
    "drawer": "9",
    "active": true
  },
  {
    "drug_id": "D076",
    "generic_name": "Dicloxacillin sodium",
    "strength": "250mg",
    "dosage_form": "Tablet",
    "trade_name": "c-clock 250 (cmed)",
    "unit": "เม็ด",
    "purchase_price": 1.29,
    "sale_price": 3,
    "stock": 234,
    "min_stock": 10,
    "drawer": "9",
    "active": true
  },
  {
    "drug_id": "D077",
    "generic_name": "Dicloxacillin sodium",
    "strength": "500mg",
    "dosage_form": "Tablet",
    "trade_name": "c-clock500 (cmed)",
    "unit": "เม็ด",
    "purchase_price": 1.46,
    "sale_price": 3.5,
    "stock": 24,
    "min_stock": 10,
    "drawer": "9",
    "active": true
  },
  {
    "drug_id": "D078",
    "generic_name": "Dimenhydrinate",
    "strength": "50mg",
    "dosage_form": "Tablet",
    "trade_name": "DIMENHIDINATEURS 100X10'S",
    "unit": "เม็ด",
    "purchase_price": 0.25,
    "sale_price": 1,
    "stock": 8,
    "min_stock": 10,
    "drawer": "11",
    "active": true
  },
  {
    "drug_id": "D079",
    "generic_name": "Dimenhydrinate",
    "strength": "1 ml",
    "dosage_form": "Tube",
    "trade_name": "Divomit injection 1 ml / Divomit injection 1 ml",
    "unit": "หลอด",
    "purchase_price": 0.47,
    "sale_price": 40,
    "stock": 0,
    "min_stock": 10,
    "drawer": "11",
    "active": true
  },
  {
    "drug_id": "D080",
    "generic_name": "Dimenhydrinate",
    "strength": "50mg",
    "dosage_form": "Tablet",
    "trade_name": "Dimenhyclinate 50mg NI. เหลืองกลม",
    "unit": "เม็ด",
    "purchase_price": 0.18,
    "sale_price": 1,
    "stock": 800,
    "min_stock": 10,
    "drawer": "11",
    "active": true
  },
  {
    "drug_id": "D081",
    "generic_name": "Lidocaine hydrochloride",
    "strength": "30gm",
    "dosage_form": "Tube",
    "trade_name": "Docaine jelly 2% 30gm",
    "unit": "หลอด",
    "purchase_price": 85,
    "sale_price": 100,
    "stock": 0,
    "min_stock": 10,
    "drawer": "7",
    "active": true
  },
  {
    "drug_id": "D082",
    "generic_name": "Docusate sodium",
    "strength": "15ml",
    "dosage_form": "Bottle",
    "trade_name": "Dewax หยอดหู 15ml",
    "unit": "ขวด",
    "purchase_price": 54,
    "sale_price": 70,
    "stock": 1,
    "min_stock": 10,
    "drawer": "7",
    "active": true
  },
  {
    "drug_id": "D083",
    "generic_name": "Domperidone",
    "strength": "10 mg",
    "dosage_form": "Tablet",
    "trade_name": "Domper-m",
    "unit": "เม็ด",
    "purchase_price": 0.22,
    "sale_price": 1,
    "stock": 400,
    "min_stock": 10,
    "drawer": "1",
    "active": true
  },
  {
    "drug_id": "D084",
    "generic_name": "Domperidone",
    "strength": "30ml",
    "dosage_form": "Bottle",
    "trade_name": "Domperdone 30ml",
    "unit": "ขวด",
    "purchase_price": 9.5,
    "sale_price": 25,
    "stock": 300,
    "min_stock": 10,
    "drawer": "ด",
    "active": true
  },
  {
    "drug_id": "D085",
    "generic_name": "Hydrocortisone acetate + Benzocaine + Zinc oxide",
    "strength": "7.5MG",
    "dosage_form": "stick",
    "trade_name": "DOPROCT เหน็บIOS(HYDROCORTISONE7.5MG) A03",
    "unit": "แท่ง",
    "purchase_price": 5.38,
    "sale_price": 12,
    "stock": 16,
    "min_stock": 10,
    "drawer": "4",
    "active": true
  },
  {
    "drug_id": "D086",
    "generic_name": "Doxazosin",
    "strength": "2mg",
    "dosage_form": "Tablet",
    "trade_name": "CARDOXA /SPS",
    "unit": "เม็ด",
    "purchase_price": 0.95,
    "sale_price": 2,
    "stock": 110,
    "min_stock": 10,
    "drawer": "2",
    "active": true
  },
  {
    "drug_id": "D087",
    "generic_name": "Doxycycline",
    "strength": "100mg",
    "dosage_form": "Tablet",
    "trade_name": "DOXY CAP",
    "unit": "เม็ด",
    "purchase_price": 0.8,
    "sale_price": 3,
    "stock": 50,
    "min_stock": 10,
    "drawer": "9",
    "active": true
  },
  {
    "drug_id": "D088",
    "generic_name": "Enalapril maleate",
    "strength": "5mg",
    "dosage_form": "Tablet",
    "trade_name": "Anapril/Berlin",
    "unit": "เม็ด",
    "purchase_price": 0.6,
    "sale_price": 2,
    "stock": 59,
    "min_stock": 10,
    "drawer": "2",
    "active": true
  },
  {
    "drug_id": "D089",
    "generic_name": "Enalapril maleate",
    "strength": "20mg",
    "dosage_form": "Tablet",
    "trade_name": "Anapril/Berlin",
    "unit": "เม็ด",
    "purchase_price": 1.6,
    "sale_price": 3,
    "stock": 60,
    "min_stock": 10,
    "drawer": "2",
    "active": true
  },
  {
    "drug_id": "D090",
    "generic_name": "Enalapril maleate",
    "strength": "5mg",
    "dosage_form": "Tablet",
    "trade_name": "Anapril - S /Berlin",
    "unit": "เม็ด",
    "purchase_price": 0.6,
    "sale_price": 2,
    "stock": 200,
    "min_stock": 10,
    "drawer": "2",
    "active": true
  },
  {
    "drug_id": "D091",
    "generic_name": "Enalapril maleate",
    "strength": "20mg",
    "dosage_form": "Tablet",
    "trade_name": "Anapril -S /Berlin",
    "unit": "เม็ด",
    "purchase_price": 1.98,
    "sale_price": 3,
    "stock": 100,
    "min_stock": 10,
    "drawer": "2",
    "active": true
  },
  {
    "drug_id": "D092",
    "generic_name": "Escitalopram",
    "strength": "10mg",
    "dosage_form": "Tablet",
    "trade_name": "ESIDEP 10MG.7'S. 4 แผง / Sun Pharma",
    "unit": "เม็ด",
    "purchase_price": 11.71,
    "sale_price": 15,
    "stock": 0,
    "min_stock": 10,
    "drawer": "11",
    "active": true
  },
  {
    "drug_id": "D093",
    "generic_name": "Etoricoxib",
    "strength": "120mg",
    "dosage_form": "Tablet",
    "trade_name": "ARCOXIA 120MG 5'S กล่องละแผง",
    "unit": "เม็ด",
    "purchase_price": 45.6,
    "sale_price": 30,
    "stock": 5,
    "min_stock": 10,
    "drawer": "6",
    "active": true
  },
  {
    "drug_id": "D094",
    "generic_name": "Etoricoxib",
    "strength": "90mg",
    "dosage_form": "Tablet",
    "trade_name": "Torcozia 90mg",
    "unit": "เม็ด",
    "purchase_price": 9.4,
    "sale_price": 25,
    "stock": 0,
    "min_stock": 10,
    "drawer": "6",
    "active": true
  },
  {
    "drug_id": "D095",
    "generic_name": "Etoricoxib",
    "strength": "120mg",
    "dosage_form": "Tablet",
    "trade_name": "Etomed 120 /media pharma",
    "unit": "เม็ด",
    "purchase_price": 14.5,
    "sale_price": 30,
    "stock": 120,
    "min_stock": 10,
    "drawer": "6",
    "active": true
  },
  {
    "drug_id": "D096",
    "generic_name": "Cooling Gel Sheet (แผ่นเจลลดไข้)",
    "strength": "แผ่น",
    "dosage_form": "Other",
    "trade_name": "ByeBye fever เด็กโต",
    "unit": "แผ่น",
    "purchase_price": 11.83,
    "sale_price": 20,
    "stock": 8,
    "min_stock": 10,
    "drawer": "7",
    "active": true
  },
  {
    "drug_id": "D097",
    "generic_name": "Ferrous fumarate",
    "strength": "200mg",
    "dosage_form": "Tablet",
    "trade_name": "Femarate 200mg ฟีมาเลต ขายเป็นแผง",
    "unit": "เม็ด",
    "purchase_price": 3.5,
    "sale_price": 4,
    "stock": 0,
    "min_stock": 10,
    "drawer": "12",
    "active": true
  },
  {
    "drug_id": "D098",
    "generic_name": "Fenofibrate",
    "strength": "160mg",
    "dosage_form": "Tablet",
    "trade_name": "Fibril/Berlin",
    "unit": "เม็ด",
    "purchase_price": 5.9,
    "sale_price": 7,
    "stock": 10,
    "min_stock": 10,
    "drawer": "3",
    "active": true
  },
  {
    "drug_id": "D099",
    "generic_name": "Ferrous fumarate",
    "strength": "200mg",
    "dosage_form": "Tablet",
    "trade_name": "Ferrous fumarate /ธาตุเหล็กcentral",
    "unit": "เม็ด",
    "purchase_price": 0.19,
    "sale_price": 2,
    "stock": 1000,
    "min_stock": 10,
    "drawer": "12",
    "active": true
  },
  {
    "drug_id": "D100",
    "generic_name": "Cooling Gel Sheet (แผ่นเจลลดไข้)",
    "strength": "",
    "dosage_form": "Other",
    "trade_name": "Fever kold เด็กโตและผู้ใหญ่ 5x12cm",
    "unit": "ชิ้น",
    "purchase_price": 16.33,
    "sale_price": 30,
    "stock": 30,
    "min_stock": 10,
    "drawer": "7",
    "active": true
  },
  {
    "drug_id": "D101",
    "generic_name": "Fexofenadine",
    "strength": "180mg",
    "dosage_form": "Tablet",
    "trade_name": "AVAFAST 180MG 10 ring TELFAST [MILLIMED]",
    "unit": "เม็ด",
    "purchase_price": 5.48,
    "sale_price": 8,
    "stock": 0,
    "min_stock": 10,
    "drawer": "3",
    "active": true
  },
  {
    "drug_id": "D102",
    "generic_name": "Finasteride",
    "strength": "5 mg",
    "dosage_form": "Tablet",
    "trade_name": "Harifin -5 / TO",
    "unit": "เม็ด",
    "purchase_price": 8.67,
    "sale_price": 13,
    "stock": 40,
    "min_stock": 10,
    "drawer": "2",
    "active": true
  },
  {
    "drug_id": "D103",
    "generic_name": "Amoxicillin + Clavulanic acid",
    "strength": "1000mg.",
    "dosage_form": "Tablet",
    "trade_name": "1000MG 10'S[BERLIN]",
    "unit": "เม็ด",
    "purchase_price": 9.3,
    "sale_price": 12,
    "stock": 0,
    "min_stock": 10,
    "drawer": "9",
    "active": true
  },
  {
    "drug_id": "D104",
    "generic_name": "Flunarizine",
    "strength": "5mg",
    "dosage_form": "Tablet",
    "trade_name": "Sovelium  แดงเทา ขายเป็นแผง",
    "unit": "เม็ด",
    "purchase_price": 0.5,
    "sale_price": 1.5,
    "stock": 100,
    "min_stock": 10,
    "drawer": "11",
    "active": true
  },
  {
    "drug_id": "D105",
    "generic_name": "Folic acid",
    "strength": "5 mg",
    "dosage_form": "Tablet",
    "trade_name": "Folimed 5mg",
    "unit": "เม็ด",
    "purchase_price": 0.29,
    "sale_price": 1,
    "stock": 100,
    "min_stock": 10,
    "drawer": "12",
    "active": true
  },
  {
    "drug_id": "D106",
    "generic_name": "Furosemide",
    "strength": "40 mg.",
    "dosage_form": "Tablet",
    "trade_name": "Furetic",
    "unit": "เม็ด",
    "purchase_price": 4.2,
    "sale_price": 8,
    "stock": 45,
    "min_stock": 10,
    "drawer": "3",
    "active": true
  },
  {
    "drug_id": "D107",
    "generic_name": "Fusidic acid",
    "strength": "5g",
    "dosage_form": "Tube",
    "trade_name": "Fusidic acid 2%",
    "unit": "หลอด",
    "purchase_price": 87,
    "sale_price": 110,
    "stock": 6,
    "min_stock": 10,
    "drawer": "8",
    "active": true
  },
  {
    "drug_id": "D108",
    "generic_name": "Gabapentin",
    "strength": "100mg",
    "dosage_form": "Tablet",
    "trade_name": "GABAPENTIN 1Q0MG 10X108ชียว)>>>230G / GPO",
    "unit": "เม็ด",
    "purchase_price": 1.65,
    "sale_price": 3,
    "stock": 70,
    "min_stock": 10,
    "drawer": "11",
    "active": true
  },
  {
    "drug_id": "D109",
    "generic_name": "Sodium alginate + Sodium bicarbonate + Calcium carbonate",
    "strength": "",
    "dosage_form": "Tablet",
    "trade_name": "Gaviscon dual ชมพู เม็ด",
    "unit": "เม็ด",
    "purchase_price": 12.44,
    "sale_price": 16,
    "stock": 16,
    "min_stock": 10,
    "drawer": "1",
    "active": true
  },
  {
    "drug_id": "D110",
    "generic_name": "Gemfibrozil",
    "strength": "600mg",
    "dosage_form": "Tablet",
    "trade_name": "Hidil 600mg ขายเป็นแผง / Berlin",
    "unit": "เม็ด",
    "purchase_price": 3.45,
    "sale_price": 6,
    "stock": 200,
    "min_stock": 10,
    "drawer": "3",
    "active": true
  },
  {
    "drug_id": "D111",
    "generic_name": "Gemfibrozil",
    "strength": "300mg",
    "dosage_form": "Tablet",
    "trade_name": "Hidil 300mg ขายเป็นแผง / Berlin",
    "unit": "เม็ด",
    "purchase_price": 2,
    "sale_price": 4,
    "stock": 39,
    "min_stock": 10,
    "drawer": "3",
    "active": true
  },
  {
    "drug_id": "D112",
    "generic_name": "COVID-19 / Influenza A&B Antigen Test Kit (ATK)",
    "strength": "COVID-19 ATK",
    "dosage_form": "Box",
    "trade_name": "GICA 3 INI TEST",
    "unit": "กล่อง",
    "purchase_price": 44,
    "sale_price": 65,
    "stock": 0,
    "min_stock": 10,
    "drawer": "ห",
    "active": true
  },
  {
    "drug_id": "D113",
    "generic_name": "Glipizide",
    "strength": "5 mg.",
    "dosage_form": "Tablet",
    "trade_name": "GLIPIZIDE SMG 10X10/S[MS] GLIPIMED/medicine supply",
    "unit": "เม็ด",
    "purchase_price": 0.55,
    "sale_price": 2,
    "stock": 50,
    "min_stock": 10,
    "drawer": "3",
    "active": true
  },
  {
    "drug_id": "D114",
    "generic_name": "Glucose",
    "strength": "50 ml.",
    "dosage_form": "Set",
    "trade_name": "Glucose 50% 50ml anb",
    "unit": "ชุด",
    "purchase_price": 19.5,
    "sale_price": 30,
    "stock": 0,
    "min_stock": 10,
    "drawer": "ห",
    "active": true
  },
  {
    "drug_id": "D115",
    "generic_name": "COVID-19 / Influenza A&B Antigen Test Kit (ATK)",
    "strength": "2 IN I",
    "dosage_form": "Box",
    "trade_name": "ATK HIP 2 IN I (HIP BIOTECH] I TEST",
    "unit": "กล่อง",
    "purchase_price": 16.2,
    "sale_price": 50,
    "stock": 0,
    "min_stock": 10,
    "drawer": "ห",
    "active": true
  },
  {
    "drug_id": "D116",
    "generic_name": "Antazoline hydrochloride + Tetrahydrozoline hydrochloride",
    "strength": "5 ml",
    "dosage_form": "Box",
    "trade_name": "HISTA-OPH 5CC",
    "unit": "กล่อง",
    "purchase_price": 26.92,
    "sale_price": 40,
    "stock": 7,
    "min_stock": 10,
    "drawer": "10",
    "active": true
  },
  {
    "drug_id": "D117",
    "generic_name": "Hydralazine",
    "strength": "50mg",
    "dosage_form": "Tablet",
    "trade_name": "TO",
    "unit": "เม็ด",
    "purchase_price": 1.12,
    "sale_price": 2.5,
    "stock": 457,
    "min_stock": 10,
    "drawer": "2",
    "active": true
  },
  {
    "drug_id": "D118",
    "generic_name": "Hydralazine",
    "strength": "25mg",
    "dosage_form": "Tablet",
    "trade_name": "Cesoline W",
    "unit": "เม็ด",
    "purchase_price": 1.6,
    "sale_price": 2,
    "stock": 50,
    "min_stock": 10,
    "drawer": "2",
    "active": true
  },
  {
    "drug_id": "D119",
    "generic_name": "Hypromellose (Hydroxypropyl methylcellulose)",
    "strength": "10ml",
    "dosage_form": "Box",
    "trade_name": "Lac-OPH / SENG THAI COMPANY",
    "unit": "กล่อง",
    "purchase_price": 33,
    "sale_price": 40,
    "stock": 7,
    "min_stock": 10,
    "drawer": "12",
    "active": true
  },
  {
    "drug_id": "D120",
    "generic_name": "Hypromellose (Hydroxypropyl methylcellulose)",
    "strength": "10ml",
    "dosage_form": "Bottle",
    "trade_name": "Lac-oph หยอดตา",
    "unit": "ขวด",
    "purchase_price": 26.5,
    "sale_price": 40,
    "stock": 900,
    "min_stock": 10,
    "drawer": "12",
    "active": true
  },
  {
    "drug_id": "D121",
    "generic_name": "Hydrochlorothiazide",
    "strength": "25mg",
    "dosage_form": "Tablet",
    "trade_name": "HCTZ 25 MG [GPO]",
    "unit": "เม็ด",
    "purchase_price": 0.3,
    "sale_price": 1,
    "stock": 70,
    "min_stock": 10,
    "drawer": "3",
    "active": true
  },
  {
    "drug_id": "D122",
    "generic_name": "Hydroxyzine Hydrochloride",
    "strength": "25mg",
    "dosage_form": "Tablet",
    "trade_name": "Dormirax 25mg /Burapha",
    "unit": "เม็ด",
    "purchase_price": 0.59,
    "sale_price": 1,
    "stock": 200,
    "min_stock": 10,
    "drawer": "11",
    "active": true
  },
  {
    "drug_id": "D123",
    "generic_name": "Hydroxyzine Hydrochloride",
    "strength": "25mg",
    "dosage_form": "Tablet",
    "trade_name": "Dormirax 25mg /Burapha /แผง",
    "unit": "เม็ด",
    "purchase_price": 1.3,
    "sale_price": 2,
    "stock": 100,
    "min_stock": 10,
    "drawer": "11",
    "active": true
  },
  {
    "drug_id": "D124",
    "generic_name": "Hyoscine-N-butylbromide",
    "strength": "30ml.",
    "dosage_form": "Bottle",
    "trade_name": "Hyoscine star syrup 30ml",
    "unit": "ขวด",
    "purchase_price": 14.5,
    "sale_price": 30,
    "stock": 6,
    "min_stock": 10,
    "drawer": "ด",
    "active": true
  },
  {
    "drug_id": "D125",
    "generic_name": "Hyoscine-N-butylbromide",
    "strength": "10 mg",
    "dosage_form": "Tablet",
    "trade_name": "Spascopan / Bangkok lab & Cosmetic  /bkd",
    "unit": "เม็ด",
    "purchase_price": 1.4,
    "sale_price": 3,
    "stock": 300,
    "min_stock": 10,
    "drawer": "12",
    "active": true
  },
  {
    "drug_id": "D126",
    "generic_name": "Ibuprofen",
    "strength": "400 mg",
    "dosage_form": "Tablet",
    "trade_name": "TO CHEMICAL (1979)Ltd",
    "unit": "เม็ด",
    "purchase_price": 0.76,
    "sale_price": 2,
    "stock": 20,
    "min_stock": 10,
    "drawer": "5",
    "active": true
  },
  {
    "drug_id": "D127",
    "generic_name": "Ibuprofen",
    "strength": "200MG",
    "dosage_form": "Tablet",
    "trade_name": "BUMAN-200 1000'Sกลมชมพู (IBUPROFEN)",
    "unit": "เม็ด",
    "purchase_price": 0.37,
    "sale_price": 1.5,
    "stock": 800,
    "min_stock": 10,
    "drawer": "5",
    "active": true
  },
  {
    "drug_id": "D128",
    "generic_name": "Ibuprofen",
    "strength": "400 mg",
    "dosage_form": "Tablet",
    "trade_name": "Ibustar-f ขวด ขาวยาว",
    "unit": "เม็ด",
    "purchase_price": 0.83,
    "sale_price": 2,
    "stock": 110,
    "min_stock": 10,
    "drawer": "5",
    "active": true
  },
  {
    "drug_id": "D129",
    "generic_name": "Ibuprofen",
    "strength": "60CC",
    "dosage_form": "Bottle",
    "trade_name": "BUFLEX SUSP 60CC รส ส้ม",
    "unit": "ขวด",
    "purchase_price": 18,
    "sale_price": 30,
    "stock": 11,
    "min_stock": 10,
    "drawer": "ด",
    "active": true
  },
  {
    "drug_id": "D130",
    "generic_name": "Ibuprofen",
    "strength": "400MG",
    "dosage_form": "Tablet",
    "trade_name": "GOFEN /care cap",
    "unit": "เม็ด",
    "purchase_price": 7.8,
    "sale_price": 12,
    "stock": 26,
    "min_stock": 10,
    "drawer": "6",
    "active": true
  },
  {
    "drug_id": "D131",
    "generic_name": "Chamomile extract + Essential oils spray",
    "strength": "15ml",
    "dosage_form": "Box",
    "trade_name": "Kamillosan สเปรย์ 15ml",
    "unit": "กล่อง",
    "purchase_price": 144,
    "sale_price": 170,
    "stock": 6,
    "min_stock": 10,
    "drawer": "11",
    "active": true
  },
  {
    "drug_id": "D132",
    "generic_name": "Levothyroxine sodium",
    "strength": "100mg",
    "dosage_form": "Tablet",
    "trade_name": "THYROSIT 100MG 50X10'S",
    "unit": "เม็ด",
    "purchase_price": 2.5,
    "sale_price": 4,
    "stock": 5,
    "min_stock": 10,
    "drawer": "11",
    "active": true
  },
  {
    "drug_id": "D133",
    "generic_name": "Lorazepam",
    "strength": "1MG.",
    "dosage_form": "Tablet",
    "trade_name": "Lorazepam",
    "unit": "เม็ด",
    "purchase_price": 0.7,
    "sale_price": 5,
    "stock": 800,
    "min_stock": 10,
    "drawer": "11",
    "active": true
  },
  {
    "drug_id": "D134",
    "generic_name": "Losartan potassium",
    "strength": "50MG",
    "dosage_form": "Tablet",
    "trade_name": "LOSARTAN /GPO",
    "unit": "เม็ด",
    "purchase_price": 1.13,
    "sale_price": 3,
    "stock": 70,
    "min_stock": 10,
    "drawer": "2",
    "active": true
  },
  {
    "drug_id": "D135",
    "generic_name": "Losartan potassium",
    "strength": "50MG",
    "dosage_form": "Tablet",
    "trade_name": "LANZAAR 50MG 10X10S[BERLIN]",
    "unit": "เม็ด",
    "purchase_price": 1.83,
    "sale_price": 3,
    "stock": 60,
    "min_stock": 10,
    "drawer": "2",
    "active": true
  },
  {
    "drug_id": "D136",
    "generic_name": "Itraconazole",
    "strength": "100mg",
    "dosage_form": "Tablet",
    "trade_name": "Spornar 100mg ขายเป็นแผง",
    "unit": "เม็ด",
    "purchase_price": 5,
    "sale_price": 8,
    "stock": 136,
    "min_stock": 10,
    "drawer": "12",
    "active": true
  },
  {
    "drug_id": "D137",
    "generic_name": "Clotrimazole",
    "strength": "5gm",
    "dosage_form": "Tube",
    "trade_name": "Lyma cream",
    "unit": "หลอด",
    "purchase_price": 12,
    "sale_price": 30,
    "stock": 11,
    "min_stock": 10,
    "drawer": "7",
    "active": true
  },
  {
    "drug_id": "D138",
    "generic_name": "Clotrimazole",
    "strength": "15gm",
    "dosage_form": "Tube",
    "trade_name": "Lyma cream",
    "unit": "หลอด",
    "purchase_price": 24,
    "sale_price": 50,
    "stock": 5,
    "min_stock": 10,
    "drawer": "7",
    "active": true
  },
  {
    "drug_id": "D139",
    "generic_name": "Manidipine",
    "strength": "20MG.",
    "dosage_form": "Tablet",
    "trade_name": "Cardipot / BERLIN",
    "unit": "เม็ด",
    "purchase_price": 3.8,
    "sale_price": 5,
    "stock": 220,
    "min_stock": 10,
    "drawer": "2",
    "active": true
  },
  {
    "drug_id": "D140",
    "generic_name": "Mefenamic acid",
    "strength": "500MG",
    "dosage_form": "Tablet",
    "trade_name": "PONSTAN",
    "unit": "เม็ด",
    "purchase_price": 4.4,
    "sale_price": 6,
    "stock": 7,
    "min_stock": 10,
    "drawer": "6",
    "active": true
  },
  {
    "drug_id": "D141",
    "generic_name": "Metformin hydrochloride",
    "strength": "500mg",
    "dosage_form": "Tablet",
    "trade_name": "METFORMIN 500MG SOXIO'S [THUWN]",
    "unit": "เม็ด",
    "purchase_price": 0.5,
    "sale_price": 2,
    "stock": 0,
    "min_stock": 10,
    "drawer": "3",
    "active": true
  },
  {
    "drug_id": "D142",
    "generic_name": "Metformin hydrochloride",
    "strength": "500mg",
    "dosage_form": "Tablet",
    "trade_name": "METFORMIN /media pharma",
    "unit": "เม็ด",
    "purchase_price": 0.36,
    "sale_price": 2,
    "stock": 251,
    "min_stock": 10,
    "drawer": "3",
    "active": true
  },
  {
    "drug_id": "D143",
    "generic_name": "Methyl salicylate + Menthol + Eugenol",
    "strength": "30 mg",
    "dosage_form": "Tube",
    "trade_name": "FLANIL / BIOPHARM",
    "unit": "หลอด",
    "purchase_price": 24,
    "sale_price": 35,
    "stock": 12,
    "min_stock": 10,
    "drawer": "8",
    "active": true
  },
  {
    "drug_id": "D144",
    "generic_name": "Metoclopramide hydrochloride",
    "strength": "10mg.",
    "dosage_form": "Tablet",
    "trade_name": "Medicplex / สหแพทย์",
    "unit": "เม็ด",
    "purchase_price": 0.25,
    "sale_price": 2,
    "stock": 900,
    "min_stock": 10,
    "drawer": "10",
    "active": true
  },
  {
    "drug_id": "D145",
    "generic_name": "Metronidazole",
    "strength": "400mg",
    "dosage_form": "Tablet",
    "trade_name": "400 สหแพทย์ ขายเป็นแผง",
    "unit": "เม็ด",
    "purchase_price": 1,
    "sale_price": 3,
    "stock": 34,
    "min_stock": 10,
    "drawer": "9",
    "active": true
  },
  {
    "drug_id": "D146",
    "generic_name": "Ergotamine tartrate + Caffeine",
    "strength": "100 mg",
    "dosage_form": "Tablet",
    "trade_name": "Migana (ไมเกนน่า เม็ด) / T.man PHARMA",
    "unit": "เม็ด",
    "purchase_price": 2.2,
    "sale_price": 4,
    "stock": 100,
    "min_stock": 10,
    "drawer": "6",
    "active": true
  },
  {
    "drug_id": "D147",
    "generic_name": "Magnesium hydroxide (Milk of Magnesia)",
    "strength": "240ml.",
    "dosage_form": "Bottle",
    "trade_name": "MM / สหแพทย์ Medic pharma",
    "unit": "ขวด",
    "purchase_price": 24,
    "sale_price": 35,
    "stock": 10,
    "min_stock": 10,
    "drawer": "4",
    "active": true
  },
  {
    "drug_id": "D148",
    "generic_name": "Ispaghula husk (Psyllium husk)",
    "strength": "5 mg",
    "dosage_form": "Sachet",
    "trade_name": "Mucilin SF / berlin",
    "unit": "ซอง",
    "purchase_price": 1.62,
    "sale_price": 4,
    "stock": 44,
    "min_stock": 10,
    "drawer": "4",
    "active": true
  },
  {
    "drug_id": "D149",
    "generic_name": "Zinc gluconate lozenges",
    "strength": "10g",
    "dosage_form": "ซอง",
    "trade_name": "Mybacin เม็คอมผสมซิ้ง รสส้ม ขายเป็นซอง",
    "unit": "ซอง",
    "purchase_price": 7.15,
    "sale_price": 10,
    "stock": 36,
    "min_stock": 10,
    "drawer": "10",
    "active": true
  },
  {
    "drug_id": "D150",
    "generic_name": "Naproxen",
    "strength": "250 mg.",
    "dosage_form": "Tablet",
    "trade_name": "NAPROXEN",
    "unit": "เม็ด",
    "purchase_price": 2.05,
    "sale_price": 3,
    "stock": 42,
    "min_stock": 10,
    "drawer": "6",
    "active": true
  },
  {
    "drug_id": "D151",
    "generic_name": "Neomycin + Polymyxin B + Gramicidin",
    "strength": "5CC",
    "dosage_form": "Bottle",
    "trade_name": "POLY-OPH",
    "unit": "ขวด",
    "purchase_price": 24,
    "sale_price": 40,
    "stock": 9,
    "min_stock": 10,
    "drawer": "12",
    "active": true
  },
  {
    "drug_id": "D152",
    "generic_name": "Norfloxacin",
    "strength": "400 mg",
    "dosage_form": "Tablet",
    "trade_name": "T-MAN 10X10'S(CROSSA-400",
    "unit": "เม็ด",
    "purchase_price": 1.3,
    "sale_price": 4,
    "stock": 0,
    "min_stock": 10,
    "drawer": "9",
    "active": true
  },
  {
    "drug_id": "D153",
    "generic_name": "Norfloxacin",
    "strength": "400MG",
    "dosage_form": "Tablet",
    "trade_name": "NORFLOXIN 400 MG 500S' TO C02",
    "unit": "เม็ด",
    "purchase_price": 0.95,
    "sale_price": 3,
    "stock": 300,
    "min_stock": 10,
    "drawer": "9",
    "active": true
  },
  {
    "drug_id": "D154",
    "generic_name": "Norfloxacin",
    "strength": "400MG",
    "dosage_form": "Tablet",
    "trade_name": "Norfloxstar 400mg sevenstar",
    "unit": "เม็ด",
    "purchase_price": 1.35,
    "sale_price": 3,
    "stock": 220,
    "min_stock": 10,
    "drawer": "9",
    "active": true
  },
  {
    "drug_id": "D155",
    "generic_name": "Omeprazole",
    "strength": "20mg",
    "dosage_form": "Tablet",
    "trade_name": "Moprix",
    "unit": "เม็ด",
    "purchase_price": 3.07,
    "sale_price": 6,
    "stock": 42,
    "min_stock": 10,
    "drawer": "1",
    "active": true
  },
  {
    "drug_id": "D156",
    "generic_name": "Omeprazole",
    "strength": "20mg",
    "dosage_form": "Tablet",
    "trade_name": "Omicap-20 ขายเป็นแผง",
    "unit": "เม็ด",
    "purchase_price": 0.6,
    "sale_price": 3,
    "stock": 540,
    "min_stock": 10,
    "drawer": "1",
    "active": true
  },
  {
    "drug_id": "D157",
    "generic_name": "Sodium alginate + Sodium bicarbonate + Calcium carbonate",
    "strength": "10mg.",
    "dosage_form": "Sachet",
    "trade_name": "ONE GERD IOML สูตร GAVISCON 12ชอง/กล่อง",
    "unit": "ซอง",
    "purchase_price": 9.33,
    "sale_price": 14,
    "stock": 4,
    "min_stock": 10,
    "drawer": "1",
    "active": true
  },
  {
    "drug_id": "D158",
    "generic_name": "Orphenadrine citrate + Paracetamol",
    "strength": "500 mg.",
    "dosage_form": "Tablet",
    "trade_name": "Noraphen",
    "unit": "เม็ด",
    "purchase_price": 0.44,
    "sale_price": 1.5,
    "stock": 240,
    "min_stock": 10,
    "drawer": "5",
    "active": true
  },
  {
    "drug_id": "D159",
    "generic_name": "Orphenadrine citrate + Paracetamol",
    "strength": "500 mg.",
    "dosage_form": "Tablet",
    "trade_name": "Paradine / media pharma",
    "unit": "เม็ด",
    "purchase_price": 0.35,
    "sale_price": 1.5,
    "stock": 200,
    "min_stock": 10,
    "drawer": "5",
    "active": true
  },
  {
    "drug_id": "D160",
    "generic_name": "Oral Rehydration Salts (ORS)",
    "strength": "20mg",
    "dosage_form": "Sachet",
    "trade_name": "D-LYTE (รสส้ม)(1X50S)(ORS) 202",
    "unit": "ซอง",
    "purchase_price": 3.4,
    "sale_price": 10,
    "stock": 7,
    "min_stock": 10,
    "drawer": "4",
    "active": true
  },
  {
    "drug_id": "D161",
    "generic_name": "Oral Rehydration Salts (ORS)",
    "strength": "3.3mg",
    "dosage_form": "Sachet",
    "trade_name": "Oreda ส้ม ซองเล็ก 3.3 gm",
    "unit": "ซอง",
    "purchase_price": 1.8,
    "sale_price": 5,
    "stock": 36,
    "min_stock": 10,
    "drawer": "4",
    "active": true
  },
  {
    "drug_id": "D162",
    "generic_name": "Oxymetazoline hydrochloride",
    "strength": "",
    "dosage_form": "Bottle",
    "trade_name": "liadin nasal decongest spray la'ปรย์ 0.05%",
    "unit": "ขวด",
    "purchase_price": 132,
    "sale_price": 150,
    "stock": 5,
    "min_stock": 10,
    "drawer": "11",
    "active": true
  },
  {
    "drug_id": "D163",
    "generic_name": "Paracetamol",
    "strength": "325 mg.",
    "dosage_form": "Tablet",
    "trade_name": "ASUMOL 325MG (W) 1000'S(PARA)",
    "unit": "เม็ด",
    "purchase_price": 0.17,
    "sale_price": 1,
    "stock": 700,
    "min_stock": 10,
    "drawer": "5",
    "active": true
  },
  {
    "drug_id": "D164",
    "generic_name": "Paracetamol",
    "strength": "500mg.",
    "dosage_form": "Tablet",
    "trade_name": "TYLENOL 500 MG",
    "unit": "เม็ด",
    "purchase_price": 1.15,
    "sale_price": 2,
    "stock": 110,
    "min_stock": 10,
    "drawer": "5",
    "active": true
  },
  {
    "drug_id": "D165",
    "generic_name": "Paracetamol",
    "strength": "500mg.",
    "dosage_form": "Tablet",
    "trade_name": "Cemol tablets / Central Polytrading Cemol ชมพูยาว",
    "unit": "เม็ด",
    "purchase_price": 0.2,
    "sale_price": 1,
    "stock": 380,
    "min_stock": 10,
    "drawer": "5",
    "active": true
  },
  {
    "drug_id": "D166",
    "generic_name": "Paracetamol",
    "strength": "120mg.",
    "dosage_form": "Bottle",
    "trade_name": "XEBRAMOL SYRUP",
    "unit": "ขวด",
    "purchase_price": 13.75,
    "sale_price": 30,
    "stock": 7,
    "min_stock": 10,
    "drawer": "ด",
    "active": true
  },
  {
    "drug_id": "D167",
    "generic_name": "Paracetamol",
    "strength": "250mg",
    "dosage_form": "Bottle",
    "trade_name": "Kressmol-250mg(พาราเซตามอล) ฉลากส้ม syrub 60 ml.",
    "unit": "ขวด",
    "purchase_price": 18,
    "sale_price": 30,
    "stock": 11,
    "min_stock": 10,
    "drawer": "ด",
    "active": true
  },
  {
    "drug_id": "D168",
    "generic_name": "Roxithromycin",
    "strength": "150mg",
    "dosage_form": "Bottle",
    "trade_name": "POLIROXIN TAB 50X10S[POLIPHARM]",
    "unit": "เม็ด",
    "purchase_price": 1.17,
    "sale_price": 3,
    "stock": 7,
    "min_stock": 10,
    "drawer": "12",
    "active": true
  },
  {
    "drug_id": "D169",
    "generic_name": "Prednisolone",
    "strength": "5mg",
    "dosage_form": "Tablet",
    "trade_name": "Prednisolone",
    "unit": "เม็ด",
    "purchase_price": 0.55,
    "sale_price": 5,
    "stock": 950,
    "min_stock": 10,
    "drawer": "10",
    "active": true
  },
  {
    "drug_id": "D170",
    "generic_name": "Pregabalin",
    "strength": "75mg.",
    "dosage_form": "Tablet",
    "trade_name": "LYBALIN 75MG.7'S.",
    "unit": "เม็ด",
    "purchase_price": 10.29,
    "sale_price": 20,
    "stock": 56,
    "min_stock": 10,
    "drawer": "5",
    "active": true
  },
  {
    "drug_id": "D171",
    "generic_name": "Propolis extract spray",
    "strength": "15ml",
    "dosage_form": "Box",
    "trade_name": "Propoliz mouth spray 15ml",
    "unit": "กล่อง",
    "purchase_price": 87,
    "sale_price": 125,
    "stock": 5,
    "min_stock": 10,
    "drawer": "11",
    "active": true
  },
  {
    "drug_id": "D172",
    "generic_name": "Propranolol Hydrochloride",
    "strength": "10mg",
    "dosage_form": "Tablet",
    "trade_name": "Cardenol 10mg /TO",
    "unit": "เม็ด",
    "purchase_price": 0.25,
    "sale_price": 2,
    "stock": 130,
    "min_stock": 10,
    "drawer": "2",
    "active": true
  },
  {
    "drug_id": "D173",
    "generic_name": "Salbutamol",
    "strength": "2mg",
    "dosage_form": "Tablet",
    "trade_name": "Saldol tab 2mg แผง",
    "unit": "เม็ด",
    "purchase_price": 2.9,
    "sale_price": 5,
    "stock": 90,
    "min_stock": 10,
    "drawer": "10",
    "active": true
  },
  {
    "drug_id": "D174",
    "generic_name": "Senna alexandrina (Senna extract)",
    "strength": "1000mg.",
    "dosage_form": "Tablet",
    "trade_name": "SENNA",
    "unit": "เม็ด",
    "purchase_price": 0.7,
    "sale_price": 2,
    "stock": 133,
    "min_stock": 10,
    "drawer": "4",
    "active": true
  },
  {
    "drug_id": "D175",
    "generic_name": "Simeticone",
    "strength": "80 mg.",
    "dosage_form": "Tablet",
    "trade_name": "Air -X / R.X. Company",
    "unit": "เม็ด",
    "purchase_price": 1.25,
    "sale_price": 3,
    "stock": 230,
    "min_stock": 10,
    "drawer": "1",
    "active": true
  },
  {
    "drug_id": "D176",
    "generic_name": "Simvastatin",
    "strength": "10MG",
    "dosage_form": "Tablet",
    "trade_name": "ZIMMEX /Interpharma",
    "unit": "เม็ด",
    "purchase_price": 0.87,
    "sale_price": 2,
    "stock": 200,
    "min_stock": 10,
    "drawer": "2",
    "active": true
  },
  {
    "drug_id": "D177",
    "generic_name": "Simvastatin",
    "strength": "20MG",
    "dosage_form": "Tablet",
    "trade_name": "ZIMMEX /Interpharma",
    "unit": "เม็ด",
    "purchase_price": 1.3,
    "sale_price": 3,
    "stock": 0,
    "min_stock": 10,
    "drawer": "2",
    "active": true
  },
  {
    "drug_id": "D178",
    "generic_name": "Simvastatin",
    "strength": "20mg",
    "dosage_form": "Tablet",
    "trade_name": "Zimva / GPO",
    "unit": "เม็ด",
    "purchase_price": 1,
    "sale_price": 3,
    "stock": 58,
    "min_stock": 10,
    "drawer": "2",
    "active": true
  },
  {
    "drug_id": "D179",
    "generic_name": "Sodium bicarbonate",
    "strength": "300 mg",
    "dosage_form": "Tablet",
    "trade_name": "DAMINT UD 1000'S(SODIUM BICARBONA",
    "unit": "เม็ด",
    "purchase_price": 0.09,
    "sale_price": 1,
    "stock": 950,
    "min_stock": 10,
    "drawer": "1",
    "active": true
  },
  {
    "drug_id": "D180",
    "generic_name": "Sulfamethoxazole + Trimethoprim (Co-trimoxazole)",
    "strength": "800mg",
    "dosage_form": "Tablet",
    "trade_name": "Mezine forte ขายเป็นแผง",
    "unit": "เม็ด",
    "purchase_price": 1.2,
    "sale_price": 3,
    "stock": 20,
    "min_stock": 10,
    "drawer": "9",
    "active": true
  },
  {
    "drug_id": "D181",
    "generic_name": "Multivitamins + L-Lysine syrup",
    "strength": "60ml",
    "dosage_form": "Bottle",
    "trade_name": "Syn-o-vits 60ml มี Lysine",
    "unit": "ขวด",
    "purchase_price": 18,
    "sale_price": 30,
    "stock": 9,
    "min_stock": 10,
    "drawer": "ด",
    "active": true
  },
  {
    "drug_id": "D182",
    "generic_name": "Betamethasone dipropionate + Salicylic acid",
    "strength": "5g",
    "dosage_form": "Box",
    "trade_name": "TENOSALIC OINTSGM [T-MAN]",
    "unit": "กล่อง",
    "purchase_price": 16.75,
    "sale_price": 30,
    "stock": 6,
    "min_stock": 10,
    "drawer": "7",
    "active": true
  },
  {
    "drug_id": "D183",
    "generic_name": "Tolperisone hydrochloride",
    "strength": "50mg",
    "dosage_form": "Tablet",
    "trade_name": "MYOXAN IIN TO SOXIOS (TOLPERISONE) B02",
    "unit": "เม็ด",
    "purchase_price": 0.25,
    "sale_price": 2,
    "stock": 260,
    "min_stock": 10,
    "drawer": "6",
    "active": true
  },
  {
    "drug_id": "D184",
    "generic_name": "Tramadol",
    "strength": "50MG",
    "dosage_form": "Tablet",
    "trade_name": "MADOLA CAPSULE 50MG / Parma land",
    "unit": "เม็ด",
    "purchase_price": 0.75,
    "sale_price": 4,
    "stock": 250,
    "min_stock": 10,
    "drawer": "5",
    "active": true
  },
  {
    "drug_id": "D185",
    "generic_name": "Tramadol hydrochloride + Paracetamol",
    "strength": "325mg",
    "dosage_form": "Tablet",
    "trade_name": "DUOCETZ",
    "unit": "เม็ด",
    "purchase_price": 9.4,
    "sale_price": 16,
    "stock": 5,
    "min_stock": 10,
    "drawer": "5",
    "active": true
  },
  {
    "drug_id": "D186",
    "generic_name": "Tramadol Hydrochloride",
    "strength": "50MG",
    "dosage_form": "Tablet",
    "trade_name": "RAMADOL / vs pharma",
    "unit": "เม็ด",
    "purchase_price": 1.3,
    "sale_price": 5,
    "stock": 190,
    "min_stock": 10,
    "drawer": "5",
    "active": true
  },
  {
    "drug_id": "D187",
    "generic_name": "Triamcinolone acetonide",
    "strength": "1g",
    "dosage_form": "Sachet",
    "trade_name": "KANOLONE/คาโนโลน",
    "unit": "ซอง",
    "purchase_price": 11.75,
    "sale_price": 14,
    "stock": 11,
    "min_stock": 10,
    "drawer": "7",
    "active": true
  },
  {
    "drug_id": "D188",
    "generic_name": "Triamcinolone acetonide",
    "strength": "5MG",
    "dosage_form": "Tube",
    "trade_name": "ZYNO CREAM 0.02% 5G[BKD",
    "unit": "หลอด",
    "purchase_price": 10,
    "sale_price": 20,
    "stock": 9,
    "min_stock": 10,
    "drawer": "7",
    "active": true
  },
  {
    "drug_id": "D189",
    "generic_name": "Triamcinolone Acetonide",
    "strength": "5MG",
    "dosage_form": "Tube",
    "trade_name": "TA 0.1% ครีม 5gm",
    "unit": "หลอด",
    "purchase_price": 20,
    "sale_price": 30,
    "stock": 6,
    "min_stock": 10,
    "drawer": "7",
    "active": true
  },
  {
    "drug_id": "D190",
    "generic_name": "Triamcinolone acetonide",
    "strength": "5MG",
    "dosage_form": "Tube",
    "trade_name": "Zyno 0.1% 5gm",
    "unit": "หลอด",
    "purchase_price": 13.5,
    "sale_price": 30,
    "stock": 7,
    "min_stock": 10,
    "drawer": "7",
    "active": true
  },
  {
    "drug_id": "D191",
    "generic_name": "Vitamin B Complex",
    "strength": "",
    "dosage_form": "Tablet",
    "trade_name": "B COMPLEX แดง สหมพทธิ์ 100XIOS MEDICPLEX",
    "unit": "เม็ด",
    "purchase_price": 0.25,
    "sale_price": 1,
    "stock": 250,
    "min_stock": 10,
    "drawer": "11",
    "active": true
  },
  {
    "drug_id": "D192",
    "generic_name": "Vitamin B Complex",
    "strength": "",
    "dosage_form": "Tablet",
    "trade_name": "Vitamin b complex แดงรูปไข่ rota",
    "unit": "เม็ด",
    "purchase_price": 0.24,
    "sale_price": 1,
    "stock": 1000,
    "min_stock": 10,
    "drawer": "11",
    "active": true
  },
  {
    "drug_id": "D193",
    "generic_name": "Vitamin C",
    "strength": "500mg",
    "dosage_form": "Tablet",
    "trade_name": "HICEE 500MG.15'S.",
    "unit": "เม็ด",
    "purchase_price": 4.07,
    "sale_price": 7,
    "stock": 45,
    "min_stock": 10,
    "drawer": "10",
    "active": true
  },
  {
    "drug_id": "D194",
    "generic_name": "Dengue NS1/IgG/IgM Rapid Test Kit",
    "strength": "",
    "dosage_form": "Other",
    "trade_name": "WONDER DENGUE IgG/IgM-NS1 ATK ชุดตรวจไข้เลือดออก (3IN1)",
    "unit": "กล่อง",
    "purchase_price": 78,
    "sale_price": 120,
    "stock": 0,
    "min_stock": 10,
    "drawer": "ห",
    "active": true
  },
  {
    "drug_id": "D195",
    "generic_name": "Traditional Thai Herbal Inhaler (ยาดมสมุนไพร)",
    "strength": "",
    "dosage_form": "Other",
    "trade_name": "ยาดมสมุนไพรไทย(ตราหนุมาน",
    "unit": "ขวด",
    "purchase_price": 8.5,
    "sale_price": 12,
    "stock": 12,
    "min_stock": 10,
    "drawer": "11",
    "active": true
  },
  {
    "drug_id": "D196",
    "generic_name": "Neomycin + Polymyxin B + Gramicidin",
    "strength": "5ml",
    "dosage_form": "Bottle",
    "trade_name": "Polyoph",
    "unit": "ขวด",
    "purchase_price": 25,
    "sale_price": 40,
    "stock": 8,
    "min_stock": 10,
    "drawer": "12",
    "active": true
  }
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = OPD_MASTER_DRUGS;
}
